language: node_js

node_js:
  - 10
  - 8

cache:
  yarn: true
  directories:
    - node_modules

script: yarn test

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
