language: node_js

services:
  - docker

node_js:
  - 8

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      script: yarn test
    - stage: release
      script: yarn semantic-release
