language: node_js

services:
  - docker

node_js:
  - 8

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: release
      node_js: lts/*
      script: npm run semantic-release
